export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
export const PRODUCTS_FAIL = "PRODUCTS_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

// admin - products
export const ADMIN_PRODUCTS_REQUEST = "ADMIN_PRODUCTS_REQUEST";
export const ADMIN_PRODUCTS_SUCCESS = "ADMIN_PRODUCTS_SUCCESS";
export const ADMIN_PRODUCTS_FAIL = "ADMIN_PRODUCTS_FAIL";

// admin - create product
export const ADMIN_CREATE_PRODUCT_REQUEST = "ADMIN_CREATE_PRODUCT_REQUEST";
export const ADMIN_CREATE_PRODUCT_SUCCESS = "ADMIN_CREATE_PRODUCT_SUCCESS";
export const ADMIN_CREATE_PRODUCT_FAIL = "ADMIN_CREATE_PRODUCT_FAIL";
export const ADMIN_CREATE_PRODUCT_RESET = "ADMIN_CREATE_PRODUCT_RESET";

// admin - update product
export const ADMIN_UPDATE_PRODUCT_REQUEST = "ADMIN_UPDATE_PRODUCT_REQUEST";
export const ADMIN_UPDATE_PRODUCT_SUCCESS = "ADMIN_UPDATE_PRODUCT_SUCCESS";
export const ADMIN_UPDATE_PRODUCT_FAIL = "ADMIN_UPDATE_PRODUCT_FAIL";
export const ADMIN_UPDATE_PRODUCT_RESET = "ADMIN_UPDATE_PRODUCT_RESET";

// admin - delete product
export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST";
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_FAIL = "ADMIN_DELETE_PRODUCT_FAIL";
export const ADMIN_DELETE_PRODUCT_RESET = "ADMIN_DELETE_PRODUCT_RESET";